2024-10-19 21:11:53

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,6 +21,11 @@ jobs:
             exit 1
           fi
 
+      - name: Create .env file
+        working-directory: ./backend
+        run: |
+          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
+
       - name: Build Docker image
         working-directory: ./backend
         run: docker build -t gymapp-backend:latest .
@@ -29,17 +34,27 @@ jobs:
         working-directory: ./backend
         run: docker save -o gymapp-backend.tar gymapp-backend:latest
 
-      - name: Change ownership and permissions of tar file
+      - name: Change ownership and permissions of files
         working-directory: ./backend
         run: |
-          sudo chown $USER:$USER gymapp-backend.tar
-          chmod 644 gymapp-backend.tar
+          sudo chown $USER:$USER gymapp-backend.tar .env
+          chmod 644 gymapp-backend.tar .env
 
-      - name: Transfer Docker tar file to server
+      - name: Ensure Target Directory Exists on Server
+        uses: appleboy/ssh-action@v0.1.8
+        with:
+          host: ${{ secrets.SERVER_IP }}
+          username: ${{ secrets.SERVER_USER }}
+          password: ${{ secrets.SERVER_PASSWORD }}
+          script: |
+            mkdir -p /home/${{ secrets.SERVER_USER }}/app/
+            chmod 755 /home/${{ secrets.SERVER_USER }}/app/
+
+      - name: Transfer files to server
         uses: appleboy/scp-action@v0.1.7
         with:
-          source: "./backend/gymapp-backend.tar"
-          target: "/home/${{ secrets.SERVER_USER }}/app/gymapp-backend.tar"
+          source: "./backend/gymapp-backend.tar,./backend/.env"
+          target: "/home/${{ secrets.SERVER_USER }}/app/"
           host: ${{ secrets.SERVER_IP }}
           username: ${{ secrets.SERVER_USER }}
           password: ${{ secrets.SERVER_PASSWORD }}
@@ -55,12 +70,11 @@ jobs:
               echo "Error: gymapp-backend.tar not found!"
               exit 1
             fi
+            if [ ! -f /home/${{ secrets.SERVER_USER }}/app/.env ]; then
+              echo "Error: .env file not found!"
+              exit 1
+            fi
             docker load -i /home/${{ secrets.SERVER_USER }}/app/gymapp-backend.tar
             docker stop gymapp-backend || true
             docker rm gymapp-backend || true
-            # 确保 /home/${{ secrets.SERVER_USER }}/app/.env 是一个文件而非目录
-            if [ -d "/home/${{ secrets.SERVER_USER }}/app/.env" ]; then
-              echo "Error: /home/${{ secrets.SERVER_USER }}/app/.env is a directory."
-              exit 1
-            fi
             docker run -d --name gymapp-backend -p 8000:8000 --env-file /home/${{ secrets.SERVER_USER }}/app/.env gymapp-backend:latest
