2024-10-20 10：19：27

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,19 +36,19 @@ jobs:
             password: ${{ secrets.SERVER_PASSWORD }}
             debug: true
         
-        - name: Verify Backend .env file on server
-          uses: appleboy/ssh-action@v0.1.8
-          with:
-            host: ${{ secrets.SERVER_IP }}
-            username: ${{ secrets.SERVER_USER }}
-            password: ${{ secrets.SERVER_PASSWORD }}
-            script: |
-              if [ ! -f /home/${{ secrets.SERVER_USER }}/app/backend/.env ]; then
-                echo "Error: Backend .env file still not found after SCP!"
-                exit 1
-              else
-                echo "Backend .env file exists."
-              fi
+      - name: Verify Backend .env file on server
+        uses: appleboy/ssh-action@v0.1.8
+        with:
+          host: ${{ secrets.SERVER_IP }}
+          username: ${{ secrets.SERVER_USER }}
+          password: ${{ secrets.SERVER_PASSWORD }}
+          script: |
+            if [ ! -f /home/${{ secrets.SERVER_USER }}/app/backend/.env ]; then
+              echo "Error: Backend .env file still not found after SCP!"
+              exit 1
+            else
+              echo "Backend .env file exists."
+            fi
         
       - name: Build Backend Docker image
         working-directory: ./backend
